{% set name = "xapian-core" %}
{% set version = "1.4.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-core-{{ version }}.tar.xz
  sha256: b168e95918a01e014fb6a6cbce26e535f80da4d4791bfa5a0e0051fcb6f950ea

build:
  number: 1
  skip: true  # [win]
  script: |
    LDFLAGS=$LDFLAGS \
    ./configure \
    --enable-static \
    CXXFLAGS=-I$PREFIX/include \
    --prefix=$PREFIX

    make && make install prefix=$PREFIX
    rm -rf $PREFIX/share/doc/xapian-core

  run_exports: {{ pin_subpackage('xapian-core', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - zlib

test:
  commands: xapian-config --cxxflags --ltlibs  # required by lang bindings

about:
  home: http://xapian.org
  license: GPL-2.0+
  license_family: GPL
  license_file: COPYING
  summary: Xapian is an Open Source Search Engine Library, written in C++.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
