{% set name = "xapian-core" %}
{% set version = "1.4.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-core-{{ version }}.tar.xz
  sha256: 975a7ac018c9d34a15cc94a3ecc883204403469f748907e5c4c64d0aec2e4949

build:
  number: 0
  skip: True  # [win]
  script: |
    LDFLAGS=$LDFLAGS \
    ./configure \
    CXXFLAGS=-I$PREFIX/include \
    --prefix=$PREFIX

    make && make install
    rm -rf $PREFIX/share/doc/xapian-core

  run_exports:
    {{ pin_subpackage('xapian-core', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - zlib

test:
  commands:
    xapian-config --version

about:
  home: http://xapian.org
  license: GPL-2.0+
  license_family: GPL
  license_file: COPYING
  summary: Xapian is an Open Source Search Engine Library, written in C++.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
