{% set name = "xapian-core" %}
{% set version = "1.4.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://oligarchy.co.uk/xapian/{{ version }}/xapian-core-{{ version }}.tar.xz
  sha256: 05884af00b06702ce486057d62a3bfbe6606cf965ada0f5ea570b328a2fa1ea8

build:
  number: 0
  skip: true  # [win]
  script: |
    LDFLAGS=$LDFLAGS \
    ./configure \
    --enable-static \
    --enable-shared \
    --prefix=$PREFIX \
    CXXFLAGS=-I$PREFIX/include

    make -j ${CPU_COUNT}
    make install prefix=$PREFIX
  run_exports:
    - {{ pin_subpackage('xapian-core', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libxapian.a
    - test -f ${PREFIX}/lib/libxapian.so  # [linux]
    - test -f ${PREFIX}/lib/libxapian.dylib  # [osx]
    - xapian-config --cxxflags --libs  # command used by language bindings

about:
  home: http://xapian.org
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Xapian is an Open Source Search Engine Library, written in C++.
  description: |
    Xapian is an Open Source search engine library which allows developers
    to add advanced indexing and search facilities to their own applications.
    It has built-in support for several families of weighting models and also
    supports a rich set of boolean query operators.
  doc_url: https://xapian.org/docs/
  dev_url: https://xapian.org/bleeding

extra:
  recipe-maintainers:
    - kohr-h
