appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: IUni3pgx2Z3H3QhleF5SIJy3niGYuWoZ+QabS1eu/Vus2y0dtq89zARo+Qx+IrpC3LZNd2dVsQoqmggLXQjOjmSXAllYNcQH+MlRerMsMw1WLYkjXjEuiwmwTVugTf/Uhf1GujRUdFW9koAcPRUKYvFh8908qU2MDFrx1dHz/LdwfaUsS5plyVIZ8hPjVxItTMSH7cRACKrkBeoPPf9KBBo+LJaAFxElKe/Q1Wnal15KP0T4P6BWKquMBQO02PhLNVBQSsOc9+D1WF0y6EyzPnysRegbwBdQ2bVxj0FSeqRRSdp1oW21s2kH9K0FLzv3DH6dtgwr1nTVH6ZGwpzhqtUOWiQj2cM7XXRH9HAkEUH5GZdTeyiZbXFYY2ASzGNlRbF6n22syrNKuYP9fWqCLjkUi3VMbk6x5+k0FPjMX7COzXWA6z6FoSHwRqi49x4ApNrOGyfpkGlJy85TUaIIlctRyXo9c6lA+fOa/bswNqZ37xTtcrFmR9tWAiipF3wBrnk2CXC50c0K6zs73Dp4EPotrLROP5rmfWJIIaA21on7xuvm6vRdgB1ebH5VdrXQVA4G9IEfPDGgac+7mLSvTNatnFHx+Q194YGp9YOdJYsKJY696pZ8AqcdLJYPhY/Iqtqev1ScqR/wINkhekH4rYcG9ygSqeOfJMjuYzDTsfA=}
